// 0$ protection by playerjs.com ^^
var v = {
  "file3_separator": "//_//",
  "bk0": "@#!@@@##$$@@",
  "bk1": "^^#@@!!@#!$",
  "bk2": "@!^^!@#@@$$$$$",
  "bk3": "^^^^^^##@",
  "bk4": "$$$####!!!!!!!",
}

function decodeString(x) {
var a;
a = x.substr(2);for(var i=4;i>-1;i--){if((v["bk"+i])){if(v["bk"+i]!=""){a = a.replace(v.file3_separator+b1(v["bk"+i]),"");}}}try{a = b2(a);}catch(e){a="";}
                function b1(str) {
                    return btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g,
                        function toSolidBytes(match, p1) {
                            return String.fromCharCode("0x" + p1);
                    }));
                }
                function b2(str) {
                    return decodeURIComponent(atob(str).split("").map(function(c) {
                        return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
                    }).join(""));
                }
				return a;
}


const main = (file_url) => {
	let decode = decodeString(file_url)
	console.log(decode)
}

main('#2WzI0MHBdaHR0cDovL3N0cmVhbS52b2lkYm9vc3QuY2MvOC8yLzMvNC8wLzMvNTUxZjQ0YjU3YWJlZjc2OTY3YW//_//Xl5eXl5eIyNAJkNDc2ODJhOGM0MWM6MjAyMzA4MjcyMjpjelI2VFZsbE9GUXdiVTkyU1VGQ1ZGTjFORlpsUkVsNGFEUmljMGR3TmtaMlMwY3pjalJVY1VkRlNXVTVWRU5aYWtoWFdVOVVlSEZCYzJsUFkyWlBOVlE1Y1dwdVZVbHRRME5MYW1oVEswRnZlR2h1TVVGUVNWRnViM3BNVGpBeVVGRm5iV1ZxTTA0dlNrVTkvZnMweDYubXA0OmhsczptYW5pZmVzdC5tM3U4IG9yIGh0dHA6Ly9zdHJlYW0udm9pZGJvb3N0LmNjLzc4MWQ2ZTY1ZGZmNjVjMTkyNjdiYjYzNWI3MDMzYzEyOjIwMjMwODI3MjI6Y3pSNlRWbGxPRlF3YlU5MlNVRkNWRk4xTkZabFJFbDRhRFJpYzBkd05rWjJTMGN6Y2pSVWNVZEZTV1U1VkVOWmFraFhXVTlVZUhGQmMybFBZMlpQTlZRNWNXcHVWVWx0UTBOTGFtaFRLMEZ2ZUdodU1VRlFTVkZ1YjNwTVRqQXlVRkZuYldWcU0wNHZTa1U5LzgvMi8zLzQvMC8zL2ZzMHg2Lm1wNCxbMzYwcF1odHRwOi8vc3RyZWFtLnZvaWRib29zdC5jYy84LzIvMy80LzAvMy81NTFmNDRiNTdhYmVmNz//_//Xl4jQEAhIUAjISQ=Y5NjdhYmQ0NzY4MmE4YzQxYzoyMDIzMDgyNzIyOmN6UjZUVmxsT0ZRd2JVOTJTVUZDVkZOMU5GWmxSRWw0YURSaWMwZHdOa1oyUzBjemNqUlVjVWRGU1dVNVZFTlpha2hYV1U5VWVIRkJjMmxQWTJaUE5WUTVjV3B1VlVsdFEwTkxhbWhUSzBGdmVHaHVNVUZRU1Z//_//QCFeXiFAI0BAJCQkJCQ=GdWIzcE1UakF5VUZGbmJXVnFNMDR2U2tVOS9mczB4Ni5tcDQ6aGxzOm1hbmlmZXN0Lm0zdTggb3IgaHR0cDovL3N0cmVhbS52b2lkYm9vc3QuY2MvNzgxZDZlNjVkZmY2NWMxOTI2N2JiNjM1YjcwMzNjMTI6MjAyMzA4MjcyMjpjelI2VFZsbE9GUXdiVTkyU1VGQ1ZGTjFORlpsUkVsNGFEUmljMGR3TmtaMlMwY3pjalJVY1VkRlNXVTVWRU5aYWtoWFdVOVVlSEZCYzJsUFkyWlBOVlE1Y1dwdVZVbHRRME5MYW1oVEswRnZlR2h1TVVGUVNWRnViM//_//JCQkIyMjIyEhISEhISE=3BNVGpBeVVGRm5iV1ZxTTA0dlNrVTkvOC8yLzMvNC8wLzMvZnMweDYubXA0LFs0ODBwXWh0dHA6Ly9zdHJlYW0udm9pZGJvb3N0LmNjLzgvMi8zLzQvMC8zLzU1MWY0NGI1N2FiZWY3Njk2N2FiZDQ3NjgyYThjNDFjOjIwMjMwODI3MjI6Y3pSNlRWbGxPRlF3YlU5MlNVRkNWRk4xTkZabFJFbDRhRFJpYzBkd05rWjJTMGN6Y2pSVWNVZEZTV1U1VkVOWmFraFhXVTlVZUh//_//QCMhQEBAIyMkJEBAGQmMybFBZMlpQTlZRNWNXcHVWVWx0UTBOTGFtaFRLMEZ2ZUdodU1VRlFTVkZ1YjNwTVRqQXlVRkZuYldWcU0wNHZTa1U5LzkxMGYzLm1wNDpobHM6bWFuaWZlc3QubTN1OCBvciBodHRwOi8vc3RyZWFtLnZvaWRib29zdC5jYy9lMzY2ZDcxNTdmZGEzMDgxNWU5MjExNDZkMjg4MGI0YzoyMDIzMDgyNzIyOmN6UjZUVmxsT0ZRd2JVOTJTVUZDVkZOMU5GWmxSRWw0YURSaWMwZHdOa1oyUzBjemNqUlVjVWRGU1dVNVZFTlpha2hYV1U5VWVIRkJjMmxQWTJaUE5WUTVjV3B1VlVsdFEwTkxhbWhUSzBGdmVHaHVNVUZRU1ZGdWIzcE1UakF5VUZGbmJXVnFNMDR2U2tVOS84LzIvMy80LzAvMy85MTBmMy5tcDQsWzcyMHBdaHR0cDovL3N0cmVhbS52b2lkYm9vc3QuY2MvOC8yLzMvNC8wLzMvNTUxZjQ0YjU3YWJlZjc2OTY3YWJkNDc2ODJhOGM0MWM6MjAyMzA4MjcyMjpjelI2VFZsbE9GUXdiVTkyU1VGQ1ZGTjFORlpsUkVsNGFEUmljMGR3TmtaMlMwY3pjalJVY1VkRlNXVTVWRU5aYWtoWFdVOVVlSEZCYzJsUFkyWlBOVlE1Y1dwdVZVbHRRME5MYW1oVEswRnZlR2h1TVVGUVNWRnViM3BNVGpBeVVGRm5iV1ZxTTA0dlNrVTkvN3JkbGkubXA0OmhsczptYW5pZmVzdC5tM3U4IG9yIGh0dHA6Ly9zdHJlYW0udm9pZGJvb3N0LmNjL2UxMDMyZTgxMzFjYWM2MTZlMGMzYzY2MzE0MGM2MjQ3OjIwMjMwODI3MjI6Y3pSNlRWbGxPRlF3YlU5MlNVRkNWRk4xTkZabFJFbDRhRFJpYzBkd05rWjJTMGN6Y2pSVWNVZEZTV1U1VkVOWmFraFhXVTlVZUhGQmMybFBZMlpQTlZRNWNXcHVWVWx0UTBOTGFtaFRLMEZ2ZUdodU1VRlFTVkZ1YjNwTVRqQXlVRkZuYldWcU0wNHZTa1U5LzgvMi8zLzQvMC8zLzdyZGxpLm1wNCxbMTA4MHBdaHR0cDovL3N0cmVhbS52b2lkYm9vc3QuY2MvOC8yLzMvNC8wLzMvNTUxZjQ0YjU3YWJlZjc2OTY3YWJkNDc2ODJhOGM0MWM6MjAyMzA4MjcyMjpjelI2VFZsbE9GUXdiVTkyU1VGQ1ZGTjFORlpsUkVsNGFEUmljMGR3TmtaMlMwY3pjalJVY1VkRlNXVTVWRU5aYWtoWFdVOVVlSEZCYzJsUFkyWlBOVlE1Y1dwdVZVbHRRME5MYW1oVEswRnZlR2h1TVVGUVNWRnViM3BNVGpBeVVGRm5iV1ZxTTA0dlNrVTkvdnprNW8ubXA0OmhsczptYW5pZmVzdC5tM3U4IG9yIGh0dHA6Ly9zdHJlYW0udm9pZGJvb3N0LmNjL2ZkYTVjNjk3YmM1N2ZmZWRjZjAzNDAyZjk4Y2RmMDk2OjIwMjMwODI3MjI6Y3pSNlRWbGxPRlF3YlU5MlNVRkNWRk4xTkZabFJFbDRhRFJpYzBkd05rWjJTMGN6Y2pSVWNVZEZTV1U1VkVOWmFraFhXVTlVZUhGQmMybFBZMlpQTlZRNWNXcHVWVWx0UTBOTGFtaFRLMEZ2ZUdodU1VRlFTVkZ1YjNwTVRqQXlVRkZuYldWcU0wNHZTa1U5LzgvMi8zLzQvMC8zL3Z6azVvLm1wNA==')
